// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwKzRimjCQ4qTaAURd_jFd8qU36q3MQpQ',
    appId: '1:916990820707:web:6dd021a6f80a491dbf9356',
    messagingSenderId: '916990820707',
    projectId: 'visitas-app-126a7',
    authDomain: 'visitas-app-126a7.firebaseapp.com',
    databaseURL: 'https://visitas-app-126a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'visitas-app-126a7.firebasestorage.app',
    measurementId: 'G-GTLKBXD1KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Ht-XDbSyE0Os0sEFXcc7y-NGhFigaNM',
    appId: '1:916990820707:android:d49be5fe93e985b3bf9356',
    messagingSenderId: '916990820707',
    projectId: 'visitas-app-126a7',
    databaseURL: 'https://visitas-app-126a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'visitas-app-126a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZYI7qEW56D2Zj0plDeUNZYw5TZivMZss',
    appId: '1:916990820707:ios:5be19ee88067ef91bf9356',
    messagingSenderId: '916990820707',
    projectId: 'visitas-app-126a7',
    databaseURL: 'https://visitas-app-126a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'visitas-app-126a7.firebasestorage.app',
    iosClientId: '916990820707-o221h9eve4dg8to3qbpkl1uo41jthsnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVisitsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZYI7qEW56D2Zj0plDeUNZYw5TZivMZss',
    appId: '1:916990820707:ios:5be19ee88067ef91bf9356',
    messagingSenderId: '916990820707',
    projectId: 'visitas-app-126a7',
    databaseURL: 'https://visitas-app-126a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'visitas-app-126a7.firebasestorage.app',
    iosClientId: '916990820707-o221h9eve4dg8to3qbpkl1uo41jthsnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVisitsFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwKzRimjCQ4qTaAURd_jFd8qU36q3MQpQ',
    appId: '1:916990820707:web:0a108029c427628abf9356',
    messagingSenderId: '916990820707',
    projectId: 'visitas-app-126a7',
    authDomain: 'visitas-app-126a7.firebaseapp.com',
    databaseURL: 'https://visitas-app-126a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'visitas-app-126a7.firebasestorage.app',
    measurementId: 'G-6P7EW33YPV',
  );

}